version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          command: |
            # gitbook cli 설치
            sudo npm install -g gitbook-cli
            gitbook install
            gitbook build
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
