version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          command: |
            docker info
      
